### ISSUE TITLE
Vision: Unification of component-level rendering related API

### ISSUE THREAD

**Issue by NamelessCoder** [TYPO3/Fluid#424]
### Introduction

This issue aims to describe a suggested vision/strategy for achieving a couple of goals:

1. The vision to adopt atomic design principles as a native Fluid feature, https://gist.github.com/NamelessCoder/f599bf955a2cb6ab46996c1207af3a2e
2. A feature request for "importable sections", https://github.com/TYPO3/Fluid/issues/358
3. A new conception for template- or section-level definitions of required arguments, meaning variables that must exist when the template/section is rendered - making it work like a pseudo-ViewHelper without the need to create a PHP class.
4. The ability to document template files's required variables and create default values for optional arguments much the same way ViewHelpers are currently documented.
5. The fact that currently, Fluid enforces UpperCamelCase formats not only for PHP classes but also template files, https://github.com/TYPO3/Fluid/issues/371.

These goals all mesh together in a way that makes the following components very similar:

* A ViewHelper instance (until compiled)
* A node in a parsed-but-not-compiled template; this includes individual arguments
* A parsed section defined in a template
* A parsed template file, partial or layout (or atom, molecule or organism given point 1 above)
* The lesser known `RenderableInterface` which is accepted by `f:render` as `delegate` argument and can be implemented on arbitrary PHP classes you create instances of an assign to template variables.

Their similarities being that:

1. They all render a rendering context
2. They all have simple API methods (though some require initialisation, e.g. ViewHelpers)
3. They are all capable of carrying argument definitions (though some will have zero such arguments)

However, currently the situation is that templates use a `ParsedTemplateInterface`, ViewHelpers use a `ViewHelperInterface` - and sections defined in a template have no interface as such (is rendered through methods on parsed template's interface). How sections work is currently quite fragmented and rudimentary in Fluid and has on earlier occasions caused seemingly unrelated problems, e.g. reserved variable name `sections` because parsed sections were stored in template variables.

I'll use the word **component** to describe "an instance of something that can be rendered in Fluid" which currently includes templates (parsed instance of files/source) and ViewHelpers, and would include the atoms, molecules, organisms and sections once those are added.

Although this hints to DRY, that is not the reason for wanting to combine these interfaces. The overall point is to make Fluid transparently work with each type of component through the same API. In short, Fluid no longer would need to care of "this thing I'd like to render" is a ViewHelper, a section, a template file - or some third party invention. It would all be rendered in exactly the same way. Same argument validation and documentation capability regardless of component type.

The final item on the list is a situation that would be almost automatically solved by implementing the atomic design principles and doing it in a way that no longer enforces a certain naming or casing pragma.

### The concept

The vision is to combine the interfaces of the components described above into one set of interfaces, to turn sections into render-capable components like templates and ViewHelpers, and to adopt the new set of interfaces for all components.

**First step:**

* An `ArrayAccess` or `ArrayObject` implementation is added for `Arguments` and is initialised with `ArgumentDefinition` instances and a method to set and get argument values; providing us with a way to contain all argument processing in one place that can also pad with default values and validate consistency.
* A class `Argument` is added to wrap around those argument values and is stored in `Arguments`; this new class adopts the interface and becomes a component.
* `FluidComponentInterface` is added having methods `evaluateWithArguments(RenderingContextInterface $context, ?Arguments $arguments = null)` and `prepareArguments(RenderingContextInterface)`.
* An interface `NamedFluidComponentInterface` is added which extends `FluidComponentInterface` and adds `getName()` as the only additional method. This is then the interface used by `Argument` and can be type-hinted as return value for methods that resolve and return components by an input "name" argument.
* An interface `ParentFluidComponentInterface` which extends the `NamedFluidComponentInterface` and adds `getChildComponent(string $name): NamedFluidComponentInterface` (exception on not found, no null return), `addChildComponent(NamedFluidComponentInterface $child): void` and `importChildrenFrom(ParentFluidComponentInterface $parent): void` and explicitly is capable of resolving dotted-paths through the getter.

This creates a new structure that has no implementations yet; as such, it is completely non-breaking. The last interface, the "I'm a parent" one, will make sense if you consider we need to resolve sections from within other components, as well as "merge" sections from one component (template) into another, as per item 2 in the introduction.

Note that dotted-path support also implies sections-inside-sections becomes a possibility.

**Second step:**

* Implement this new interface on ViewHelpers - which likely means making `ViewHelperInterface` an extension of `FluidComponentInterface` but could also be achieved via implementing the new interface in `AbstractViewHelper` since it would be compatible with `ViewHelperInterface`.
* Refactor the argument validation as needed - putting it into `Arguments` or a delegate.
* Refactor code that calls ViewHelpers, programming those to the new interface instead.
* Refactor (alias, extend?) the `RenderableInterface` so a "renderable" is merely a component.

This takes care of the ViewHelper context and leaves us ready to implement argument-receiving behaviors for other components.

**Third step:**

* Refactor our `ParsedTemplateInterface` same as we did with ViewHelpers. Exact same considerations are relevant here: dual or extended interface?
* Create a new type of component, a `Section`.
* Refactor the way sections are handled, making it so a parsed template is always a `ParentFluidComponentInterface` meaning it is capable of storing and returning other components - in this case, sections.
* Refactor the API that renders sections to make it use the new component API.
* Implement section importing to allow e.g. a partial template to extend another partial template, for example through `<f:extends parent="NameOfPartial" />`; consider if the same should be possible for individual sections (if we allow sections-inside-sections as described earlier).

This leaves us in a state where rendering a section might be done by calling `$component->getChild($sectionName)->evaluateWithArguments($arguments)`. This is what would take place inside the API method `$view->renderSection()`, and it would be used in compiled templates (which instead of creating an expected PHP function name, would call `$this->getChild($sectionName)->evaluateWithArguments($renderingContext, $argumentsInstanceCreatedSomehow)`.

After this point we are able to implement argument support for the remaining components like partial templates and sections.

**Fourth step:**

* Create necessary API to define arguments in Fluid source code, e.g. `<f:argument name="foo" type="string" optional="1" default="My string" />` which would yield an `ArgumentDefinition` to reflect this argument.
* Provide these arguments from the `prepareArguments(RenderingContextInterface $context)` method in our current parsed and compiled template instances. This implies they must be compiled into our compiled templates (it would be quite easy to compile them into PHP code and simply compile the entire PHP source code for the prepareArguments method).
* Repeat this for `Section` - making it possible to use `<f:argument>` inside `<f:section>` to define a set of arguments, required types and default values.

This then concludes the entire refactoring of the component-level rendering API - and we are free to continue with the very last step: adopting the atomic design principles directly in Fluid.

**Fifth step:**

* Create a new way to register a path for "atomic resources" which works much like existing paths and allows overlays, but instead of pointing to a specific type of resource, points to *the folder that contains each of the type-specific folders like `Templates`, `Partials` etc.*.
* So, for example, you might have `/foo/bar/res/` as your "atomic resources" path and in this folder you have your `Templates`, `Layouts`, `Partials` folders - but you only define one set of paths, the rest works by expecting certain sub-folders.
* Then add additional types of sub-folders for `Atoms`, `Molecules` and `Organisms` which can contain exactly the same type of Fluid templates as the `Partials` folder currently does.
* Refactor methods that are currently explicit about what you're resolving - such as the method that resolves a partial file - and refactor it or create new API so the "type" you want to render is passed as argument rather than indicated by which method you call.

Although this last piece of the vision isn't completely thought out yet, the above should give a good idea of what would happen. In essence we would no longer distinguish between different types of Fluid templates - it means the type becomes arbitrary because you can pass any name of a type as argument and it will simply mean your template file is to be found inside *the sub-folder in your root resource path named like the type you requested*.

It *could* mean that `<f:render>` no longer uses a `partial="MyPartial"` argument but instead does something like `<f:render component="Partials/Foobar">`. This would also imply that *case-sensitivity or not, for folders and files alike, can be offloaded on the template developer entirely* - which allows us to make our resolving logic more naïve and not attempt to look for a file in multiple filename case conventions. Fluid would resolve the file you actually referenced, regardless which naming convention you used.

If we impose the `f:extends` idea on the concept of Layouts, we could effectively replace this as well so that any Fluid template can be used as "layout". Instead of referencing a certain layout, a template might instead extend that template file - or any other template file. This would however imply that extending templates does not only assimilate children components but also - somehow - is capable of delegating rendering to the parent template when there's no body of the template that is not contained within `f:section` (example: a template that uses a layout can contain content outside sections but this will be ignored - which is the same as delegating to the parent template).

### Conclusion / next steps

The benefits are hopefully clear, but a bullet-point list never hurts:

1. Instead of having 4-5 different "things that can be rendered" we reduce this number to 1.
2. Instead of having to create a PHP class if we want any argument-like behavior, we allow anything that can be rendered, to also dictate which arguments it needs and provide defaults.
3. We gain the ability to document templates or render mocks with default variables when Fluid is used in design systems like PatternLab.
4. We allow any component to extend another component (by assimilating it's children components), e.g. you no longer must define all sections contained in a partial template if you wish to extend a single section from a partial.
5. We effectively remove some of the learning curve of Fluid. New-comers would no longer need to care about file naming conventions. Beginners would rarely need to resort to PHP classes when they need an argument of a certain type to be required. And you could pick Fluid up without having a clue what a "partial" is and how it is different from any other type of template.
6. We make it somewhat easier to implement Fluid in third party frameworks that prefer different naming conventions.

Although this sounds like a huge task the scope is actually fairly limited. Because we are dealing with features that are already centralised, further combining them *does not involve refactoring all implementations*. The biggest challenges exist in the parsed- and compiled-template structures which would need to be transparently compatible and require changes to how Fluid compiles ViewHelpers.

But perhaps best of all is that this can be done as a non-breaking change and works well as five about-equal sized chunks that each would improve the situation, and have a pretty linear dependency of tasks.

**Comment by NamelessCoder** [comment]
As always, your comments are welcome. See any incompatibilities with this? Got ideas for even further reducing the learning curve or to improve the concept of "components with arguments"? Let me know!

**Comment by mbrodala** [comment]
Thanks a lot for putting this up, it sounds like a good idea to refactor the way Fluid works. A few first remarks:

- `Arguments` should have a stricter API than array access/object.
- Would this mean that I'd be able to render an `Argument`? Give it really is a component by itself.
- Does this mean that the rendering entrypoint would be `evaluateWithArguments()`?
- I'd use `ComponentInterface` instead of `FluidComponentInterface`
- I'd use `ComponentContainerInterface` instead of `ParentFluidComponentInterface` and consequently `ComponentContainerInterface::getComponent()`, `ComponentContainerInterface::addComponent()` and `ComponentContainerInterface::importComponents()`

> We allow any component to extend another component (by assimilating it's children components), e.g. you no longer must define all sections contained in a partial template if you wish to extend a single section from a partial.

This would be a killer feature and would drop a lot of migration pain on source updates. :-)

**Comment by NamelessCoder** [comment]
Thanks for the comments Mathias - some brief answers:

> `Arguments` should have a stricter API than array access/object.

Not necessarily: I would start with a vanilla implementation that has just one added (and possibly internal) behavior - the validation of arguments. This should include validation of argument *names*. But I'm not sure it actually requires additional public API beyond being an array-like object... did you have something particular in mind?

> Would this mean that I'd be able to render an `Argument`? Given it really is a component by itself.

Yes and no. You could *evaluate* it but *rendering* it would depend on what's inside the argument value - exactly like today, if you attempt to "render" (as in, directly output) an array, you get the string `Array`, but if you use that same expression as argument for a ViewHelper (or another component) then evaluation takes place. As for terminology, "evaluating" might return something not string compatible, whereas "rendering" always yields such a value. Hence the chosen API naming ;)

> Does this mean that the rendering entrypoint would be `evaluateWithArguments()`?

Yes, but nothing would prevent our implementations from having proxy methods that call the new API (in fact, that would be the compatibility strategy that would be used). For example, parsed templates may still allow `render()` which would then collect the rendering context and assigned variables in order to call the new API method.

Side note: we could actually turn a View into a component as well. Perhaps even a component container. It already shares the approximate same API as the above mentioned components. I'll consider this.

Regarding naming, sure, we can use more generic names.

Small comment about the last note, selective extension of components, I forgot to mention in the strategy above that it would also be possible to *override the arguments a certain component has specified*. This would happen by simply replacing the argument definition if the argument was re-defined in an overridden template file. It would then not be directly possible to *remove* arguments - but you could re-define any argument as optional if your override does not require it.

**Comment by NamelessCoder** [comment]
These concerns have all been addressed in the upcoming next major version, 3.0.

**Comment by mbrodala** [comment]
@NamelessCoder Are you sure that #371 is covered? I can still see `ucfirst()` calls in the 3.x code.

**Comment by NamelessCoder** [comment]
> @NamelessCoder Are you sure that https://github.com/TYPO3/Fluid/issues/371 is covered? I can still see ucfirst() calls in the 3.x code.

This perhaps needs to be clarified. We do still have ucfirst() going on, in:

* Controller action template resolving
* Layout template resolving
* Partial template resolving
* ViewHelper class name inference

All of these could probably be relaxed so that the case that comes in, is the case used when resolving. This would put the onus of dictating one or the other case, on the implementer - and depending on how/whether TYPO3 CMS wants to preserve the use of strictly UpperCamel filenames, could mean some changes need to be done in the custom TemplatePaths used there. That being said, the reason I didn't do this is that the concept of Partials and Layouts should be considered deprecated and introducing breaking changes in areas that also get deprecated, might not be the best solution. In fact, the MVC-ness of Fluid itself should be considered deprecated (the entry point to rendering should no longer be a controller action, but rather a specific file which you may choose to specify in any way you prefer, through an application-specific View in context of TYPO3 CMS).

By the way this includes the (legacy) directory scopes that you see here: https://github.com/TYPO3/Fluid/blob/e1245ed6bc6114a4e52c18d4db909acac3c00d25/src/View/TemplatePaths.php#L64 - which are used if you feed a package key to TemplatePaths and expect it to automatically infer the various default asset paths which apply to that package. These too should be considered deprecated - the replacement approach is to define a (set of) path(s) that apply to a certain namespace, as seen here: https://github.com/NamelessCoder/fluid-3-demo/blob/master/public/index.php#L38.

When I said that the concern has been addressed in 3.0 that's because the replacement concept for Layouts and Partials - Atoms - are ignorant of character cases. For example, the Fluid 3 demo package I created uses lowercase filenames for the Atoms. You _could_ use a specific case in your Atoms, like `mynamespace:MyAtom` which would look for the `MyAtom.$format` file in the Atoms path you registered for the namespace - but you are not forced to. And IMHO using lowercase Atom files gives a nicer API in the Fluid template (`mynamespace:myatom` vs. `mynamespace:MyAtom`, where I'd prefer the former).

The new logic is that you reference a Component in the template files (e.g. `myns:foobar`) which then may be an Atom template file or a ViewHelper (ViewHelpers override Atoms). The name of an Atom may use any character casing - but the class name of a ViewHelper is still inferred as UpperCamel (`myns:foobar` equals `$namespace\FoobarViewHelper`). *This part we may need to preserve, if nothing else then for backwards compatibility concern: if we remove it, every ViewHelper reference in every Fluid template file would have to be rewritten to e.g. `f:Format.Raw` and this is probably far too excessive*. And, though it isn't explicitly stated as "MUST" in PSR-4, the overwhelmingly common practice seems to be to use UpperCamel casing for class names.

Basically, the decision I ended up making was:

* Keep the enforced `ucfirst` for all contexts that are considered deprecated, to minimise the need for drastic changes that would also make a template very unlikely to be cross-compatible with Fluid 2.x and 3.x.
* But make the new concept of Components (Atoms / ViewHelpers) case agnostic, use lowercase as default but make it possible to use UpperCamel (or UPPER, or anything else) by using a sort of WYSIWYG approach where what you type in the template is 1:1 what gets used when looking up an Atom's file.
* For practical reasons, keep the enforced `ucfirst` when resolving ViewHelper class names

So when I said "all resolved" that is kind of a truth with modifications - it's not "resolved" (as in: not changed) for the legacy parts, but has been made a non-issue for the new concepts _except when it comes to ViewHelper classes_.

Whether or not we should also change the enforced `ucfirst` for Partials, Layouts and Action templates is something we can certainly discuss! I lean towards not changing it, given that those concepts are considered deprecated.

**Comment by mbrodala** [comment]
Thanks for the clarification. I can see that the risks of relaxing this for Fluid 2 are higher than the confusion for new developers.

Everything else should be discussed in #371
