### ISSUE TITLE
Protected property prevents using magic __call getter

### ISSUE THREAD

**Issue by philipmasser** [TYPO3/Fluid#483]
This commit 308f1af1a7526497f35b755d15ee87eef7fb837b adds support for (public) properties in StandardVariableProvider. However, it doesn't check the accessability. 

My project broke because of this. I happen to have a protected property `$name`. For the actual access, I rely on `__call`.

However, since 308f1af1a7526497f35b755d15ee87eef7fb837b I get a critical error `Cannot access protected property [...]Group::$name`

**Comment by NamelessCoder** [comment]
Hi @philipmasser,

This problem is fixed by https://github.com/TYPO3/Fluid/commit/b4ba01c67a56ad24d2a164c47fa4646217584ad4 which is in 2.6.5 which was released right around the same time you wrote this issue ;)

**Comment by philipmasser** [comment]
Hi,

thanks for your reply.

But the commit you mentioned is just a small code cleanup of the problematic commit. The problem still persists. In fact, it only occurred after I upgradet to 2.6.5!

Testcase:

```
class Test extends AbstractEntity {
    protected $name;
    public function __construct() {
        $this->name = 'Hello, World!';
    }
    public function __call($name, $arguments) {
        if ($name == 'getName') return $this->name;
        return '';
    }
}
```

When accessing `{obj.name}` in a fluid template where `obj` is an instance of class `Test`, I get an critical error *Cannot access protected property* as of Fluid 2.6.5.

I think a check is necessary for the case of `ACCESSOR_PUBLICPROPERTY` if the property is, well, public.

I hope you can reconsider this, as for me, the issue is not closed

My other option would be to rewrite my complete domain/repository logic

**Comment by philipmasser** [comment]
For now I found a workaround: use a magic __getter:

```
public function __get($name) {
    if (property_exists($name)) return $this->$name;
}
```

**Comment by NamelessCoder** [comment]
That is indeed a different problem, but may not be one we can fix - whichever way I think about it, we end with a bad solution:

* We can't merely change the order of these checks because `__call` is so promiscuous it says "yep, I will call anything!".
* Checking for property being public requires use of reflection which is inherently slow (and violates the visibility constraint in order to work).
* Removing `__call` (check for `is_callable` initially) support to restore previous behavior would break your use case.

I honestly lean towards saying "use `__call` at your own risk" to users and having it used only as the last resort. Yes, it does mean that implementing standard getters through `__call` and naming the internal property the same will be a broken use case because 1) PHP technically sees the property existing and 2) Fluid does not know which properties, if any, your `__call` method might handle.

Workarounds:

* Make the property actually public (I'm so oldschool that public properties are a valid solution ;))
* Rename the internal property, e.g. `protected $_name`
* Use a virtual name for the property when accessed in templates to avoid using `.name`
* Use `__get` but do so as a last resort because more magic to solve problems with magic seems like it leads to more trouble down the line.

**Comment by philipmasser** [comment]
Ah yes, I can understand your conflict here... 

I will for now go with the __get method as a temporary workaround. But in fact, I will reconsider my design to not rely on magic, now that some more magic comes to it...

I think the best option would be to actually define getters for those properties, so no need to rely on __call at all. 

Thanks for the input, you can leave the issue closed IMO

**Comment by NamelessCoder** [comment]
I prefer getters since:

1. They are explicit
2. They leave you prepared to manipulate variables received/returned
3. They allow you to enforce certain types of arguments/returns (until we get typed properties in PHP)

When we get typed properties my recommendation will switch to use public properties if you're sure you don't need to manipulate the variables. Even then you can add a getter for a public property (but risk conflicting modes of operation if getter returns a different value).

Thanks for understanding the dilemma!
